import createError from "../utils/createError.js";
import Message from "../models/message.model.js";

export const fn = async (req, res, next) => {
  try {
  } catch (err) {
    next(err);
  }
};
